### ISSUE TITLE
Questions regarding GSOC 20

### ISSUE THREAD

**Issue by dhirensr** [OWASP/Intelligent-Intrusion-Detection-System#2]
Hello @SriHarshaGajavalli ,
I was interested for submitting a proposal with this OWASP and was interested in the project.
I also saw that I would have to write the framework from scratch.
Can you tell what do I need to do before writing a proposal for getting selected? any specific tasks?

**Comment by hardlyhuman** [comment]
Hi @dhirensr 
Great to see your interest. 
As part of pre-GSoC activities, can you come up with a list of features that you can think of for this tool?

**Comment by dhirensr** [comment]
@SriHarshaGajavalli : 
1. first step would be writing some code which would collect some data for testing the model.
2. there are many datasets which could be used for training like https://www.kaggle.com/c/malware-classification ( for malware classification)

after the models are trained we could test it using the framework and with the help of UI show the user regarding the analysis from the model.

if you have any suggestions please update here.
