### ISSUE TITLE
Gsoc 2020 proposal

### ISSUE THREAD

**Issue by shashankk-agarwal** [OWASP/Intelligent-Intrusion-Detection-System#3]
Hello @SriHarshaGajavalli 
I  am interested for submitting a proposal of OWASP Intelligent Intrusion Detection System for GSOC 2020. I am working in the field of Network Security and Intrusion Detection System for the past one year .
I have some features in my mind for this tool and I want to discuss that with you.
1. Will develop Intelligent Intrusion Detection System using Artificial Intelligence which :
a. Will detect Top 10 OWASP attack and Network attacks using Machine Learning.
b. Apart from detecting the attacks it will further classify the type of attack ( Sql injection , X SITE Scripting etc.)
c. I will deploy the system in real time for existing webservers and check the efficiency of it.
2. If I get time after completing this, I can try to integrate this IDS with honeypot and can further classify the detected attacks like DOM based xss, Reflected xss to create Intrusion Prevention System.
So these are the types of features i am thinking to include in IDS. I will further inform you how I will implement this steps mentioned above. If my plan of work requires any change please do suggest me. I am looking forward for your guidance.
Thank You
Shashank Agarwal

**Comment by hardlyhuman** [comment]
This aligns with the IIDS development plan. You can start writing a formal proposal with a clear timeline of events.

**Comment by shashankk-agarwal** [comment]
@SriHarshaGajavalli 
I have few queries regarding this project : 
1. Will you provide us the dataset for training and testing (if yes then in which format like pcap or csv) or should i use dataset of my choice or could you suggest me the dataset i should use (like KDD-99) 
2. How many variations of deep learning models should i use other than LSTM. I am familiar with Fully Recurrent RNN and Elman networks and jordan networks. 
3. If time persists what should i add in the project? Some more different types of attacks like DDoS or to deploy a honeypot to make it an Intrusion Prevention System.
Thank You

**Comment by shashankk-agarwal** [comment]
Hello @SriHarshaGajavalli 
I have submitted my proposal 10 days back but you have not commented any suggestions for the improvement in the proposal .I request you to take a look at it as early as possible since very few days are left for the final proposal deadline.
Thank You

Shashank Agarwal
